name: IHub Publish Actions
author: IHub
description: IHub GitHub Gradle Publish Actions
branding:
  icon: box
  color: gray-dark
inputs:
  repoUsername:
    required: true
    description: Repo Username
  repoPassword:
    required: true
    description: Repo Password
  release:
    required: false
    description: Is Release
    default: 'false'
  signingKeyId:
    required: false
    description: signingKeyId
  signingPassword:
    required: false
    description: signingPassword
  signingSecretKey:
    required: false
    description: signingSecretKey
  parallel:
    required: false
    description: Is Parallel
    default: 'true'
  applyGithubPom:
    required: false
    description: Apply Github Pom
    default: 'true'
  publishMavenCentral:
    required: false
    description: Publish Maven Central
    default: 'true'
  useInferringVersion:
    required: false
    description: Use Inferring Version
    default: 'false'
runs:
  using: composite
  steps:
    - name: Run with Gradle
      env:
        REPO_USERNAME: ${{ inputs.repoUsername }}
        REPO_PASSWORD: ${{ inputs.repoPassword }}
        SIGNING_KEY_ID: ${{ inputs.signingKeyId }}
        SIGNING_PASSWORD: ${{ inputs.signingPassword }}
        SIGNING_SECRET_KEY: ${{ inputs.signingSecretKey }}
        USE_INFERRING_VERSION: ${{ inputs.useInferringVersion }}
      shell: bash
      run: |
        chmod +x gradlew
        ./gradlew publishToMavenCentralPortal -DiHubPublish.publishDocs=${{ inputs.release }} -DiHubPublish.publishNeedSign=${{ inputs.release }} -Dorg.gradle.parallel=${{ inputs.parallel }} -Dorg.gradle.configureondemand=${{ inputs.parallel }} -DiHubPublish.applyGithubPom=${{ inputs.applyGithubPom }} -DiHubPublish.publishMavenCentral=${{ inputs.publishMavenCentral }}
